name: skrc_wav_to_ogg
description: SKRC wav to ogg converter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  ffmpeg_kit_flutter: ^6.0.3

flutter:
  uses-material-design: true
